trigger:
  branches:
    include:
      - main   # run pipeline on pushes to main

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Setup Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node.js 20'

# 2. Install dependencies & build Next.js
- script: |
    npm ci
    npm run build
  displayName: 'Install & Build Next.js'

# 3. Prepare artifact (only required files)
- script: |
    mkdir $(Build.ArtifactStagingDirectory)/app
    cp -R .next public package.json package-lock.json $(Build.ArtifactStagingDirectory)/app
  displayName: 'Copy build artifacts'

# 4. Archive artifact
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/app'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Archive app.zip'

# 5. Deploy to Azure Web App
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'azure-sp-connection'   # your service connection
    appType: 'webAppLinux'
    WebAppName: 'nextjs-demo-app'              # your App Service name
    packageForLinux: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Deploy to Azure Web App'
