trigger:
  branches:
    include:
      - main   # run pipeline on pushes to main

# Use your self-hosted agent
pool:
  name: MyAgentPool

steps:
# 1. Checkout code
- checkout: self
  fetchDepth: 1

# 2. Setup Node.js (for local validation)
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node.js 20'

# 3. (Optional) Build locally to catch errors early
- script: |
    npm ci
    npm run build
  displayName: 'Install & Build Next.js (local check)'

# 4. Archive full source code
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/source.zip'
  displayName: 'Archive full source code'

# 5. Publish artifact (optional for history)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/source.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifact'

# 6. Deploy full source to Azure Web App (Oryx will build it)
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'azure-sp-connection'   # must match your service connection
    appType: 'webAppLinux'
    WebAppName: 'nextjs-demo-app'              # your App Service name
    packageForLinux: '$(Build.ArtifactStagingDirectory)/source.zip'
  displayName: 'Deploy full source to Azure Web App'
