trigger:
  branches:
    include:
      - main   # Run pipeline when code is pushed to main

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '20.x'
  azureServiceConnection: 'AzureSub-Connection'  # <-- replace with your Service Connection name
  webAppName: 'nextjs-demo-app'                  # <-- replace with your App Service name
  artifactName: 'nextjs-build'

stages:
- stage: Build
  displayName: 'Build Next.js App'
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - task: UseNode@1
      inputs:
        version: '$(node_version)'
      displayName: 'Install Node.js'
    - script: npm ci
      displayName: 'Install dependencies'
    - script: npm run build
      displayName: 'Build Next.js app'
    - task: ArchiveFiles@2
      displayName: 'Archive build'
      inputs:
        rootFolderOrFile: '.'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true
    - publish: $(Build.ArtifactStagingDirectory)/app.zip
      artifact: $(artifactName)

- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  jobs:
  - deployment: DeployJob
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureWebApp@1
            displayName: 'Deploy to App Service'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/$(artifactName)/app.zip'
              startupCommand: 'npm start'
